'use strict';

const express = require('express');
const crypto = require('crypto');
const router = express.Router();
const db = require('../models');
const Chat = db.Chat;
const User = db.User;
const ChatParticipant = db.ChatParticipant;

function uid(req) { return req.user?.userId || req.user?.id || req.user?.sub; }
async function loadGroup(chatId) { const chat = await Chat.findByPk(chatId); if (!chat || chat.type !== 'group' || chat.isActive === false) { const e = new Error('Group not found'); e.status = 404; throw e; } return chat; }
async function membership(chatId, userId) { return ChatParticipant.findOne({ where: { chatId, userId } }); }
async function requireMember(chat, userId) { const p = await membership(chat.id, userId); if (!p) { const e = new Error('You are not a member of this group'); e.status = 403; throw e; } return { participant: p, owner: String(chat.createdBy) === String(userId) }; }
async function requireManager(chat, userId) { const result = await requireMember(chat, userId); if (!result.owner && result.participant.role !== 'admin') { const e = new Error('Admin permission required'); e.status = 403; throw e; } return result; }
async function emitGroup(req, event, payload) { const io = req.io || global.__socketIO; if (!io) return; try { const ids = await ChatParticipant.findAll({ where: { chatId: payload.groupId }, attributes: ['userId'] }); for (const row of ids) { io.to(`user:${row.userId}`).emit(event, payload); io.to(`user_${row.userId}`).emit(event, payload); } } catch (_) {} }

function metadata(chat) { return (chat.metadata && typeof chat.metadata === 'object') ? { ...chat.metadata } : {}; }
function saveMetadata(chat, next) { return chat.update({ metadata: next, updatedAt: new Date() }); }

router.get('/:chatId/members', async (req, res) => { try { const chat = await loadGroup(req.params.chatId); await requireMember(chat, uid(req)); const rows = await ChatParticipant.findAll({ where: { chatId: chat.id }, include: [{ model: User, as: 'chatParticipantUser', attributes: ['id','username','avatar','firstName','lastName','status','lastSeen'] }], order: [['joinedAt','ASC']] }); return res.json({ success:true, data:rows.map(p=>({ id:p.userId, role:String(p.userId)===String(chat.createdBy)?'owner':(p.role||'member'), isMuted:!!p.isMuted, mutedUntil:p.mutedUntil, joinedAt:p.joinedAt, user:p.chatParticipantUser })) }); } catch(e) { return res.status(e.status||500).json({success:false,message:e.message}); } });

router.post('/:chatId/members', async (req, res) => { try { const chat=await loadGroup(req.params.chatId); await requireManager(chat,uid(req)); const userId=Number(req.body?.userId); if(!Number.isInteger(userId)||userId<=0)return res.status(400).json({success:false,message:'Valid userId is required'}); const user=await User.findByPk(userId,{attributes:['id','username','avatar','firstName','lastName','status']}); if(!user)return res.status(404).json({success:false,message:'User not found'}); if(await membership(chat.id,userId))return res.status(409).json({success:false,message:'User is already a member'}); await ChatParticipant.create({chatId:chat.id,userId,role:'member',joinedAt:new Date()}); const payload={groupId:chat.id,member:{id:user.id,userId:user.id,username:user.username,avatar:user.avatar,firstName:user.firstName,lastName:user.lastName,role:'member'},addedBy:uid(req),timestamp:new Date().toISOString()}; await emitGroup(req,'GROUP_MEMBER_ADDED',payload); await emitGroup(req,'group:member:added',payload); return res.status(201).json({success:true,data:payload.member}); } catch(e) { return res.status(e.status||500).json({success:false,message:e.message}); } });

router.delete('/:chatId/members/:userId', async (req,res)=>{ try { const chat=await loadGroup(req.params.chatId); const actor=uid(req); const {owner}=await requireManager(chat,actor); const targetId=Number(req.params.userId); if(String(targetId)===String(chat.createdBy))return res.status(403).json({success:false,message:'The group owner cannot be removed'}); const target=await membership(chat.id,targetId); if(!target)return res.status(404).json({success:false,message:'Member not found'}); if(target.role==='admin'&&!owner)return res.status(403).json({success:false,message:'Only the group owner can remove an administrator'}); await ChatParticipant.destroy({where:{chatId:chat.id,userId:targetId}}); const payload={groupId:chat.id,userId:targetId,removedBy:actor,timestamp:new Date().toISOString()}; await emitGroup(req,'GROUP_MEMBER_REMOVED',payload); await emitGroup(req,'group:member:removed',payload); return res.json({success:true,data:payload}); } catch(e){return res.status(e.status||500).json({success:false,message:e.message});} });

router.patch('/:chatId/members/:userId/role', async (req,res)=>{ try { const chat=await loadGroup(req.params.chatId); const actor=uid(req); const {owner}=await requireManager(chat,actor); const targetId=Number(req.params.userId); const role=req.body?.role; if(!['admin','member'].includes(role))return res.status(400).json({success:false,message:'Role must be admin or member'}); if(String(targetId)===String(chat.createdBy))return res.status(403).json({success:false,message:'The owner always remains owner'}); if(!owner)return res.status(403).json({success:false,message:'Only the group owner can change administrator roles'}); const target=await membership(chat.id,targetId); if(!target)return res.status(404).json({success:false,message:'Member not found'}); target.role=role; await target.save(); const payload={groupId:chat.id,userId:targetId,role,updatedBy:actor,timestamp:new Date().toISOString()}; await emitGroup(req,'GROUP_ROLE_UPDATED',payload); await emitGroup(req,'group:role_update',payload); return res.json({success:true,data:payload}); } catch(e){return res.status(e.status||500).json({success:false,message:e.message});} });

router.patch('/:chatId/members/:userId/mute', async (req,res)=>{ try { const chat=await loadGroup(req.params.chatId); const actor=uid(req); const {owner}=await requireManager(chat,actor); const targetId=Number(req.params.userId); const target=await membership(chat.id,targetId); if(!target)return res.status(404).json({success:false,message:'Member not found'}); if(String(targetId)===String(chat.createdBy))return res.status(403).json({success:false,message:'The group owner cannot be muted'}); if(target.role==='admin'&&!owner)return res.status(403).json({success:false,message:'Only the group owner can mute an administrator'}); const muted=req.body?.muted!==false; target.isMuted=muted; target.mutedUntil=muted&&req.body?.mutedUntil?new Date(req.body.mutedUntil):null; await target.save(); const payload={groupId:chat.id,userId:targetId,muted,mutedUntil:target.mutedUntil,updatedBy:actor,timestamp:new Date().toISOString()}; await emitGroup(req,'GROUP_MEMBER_MUTE_UPDATED',payload); await emitGroup(req,'group:mute',payload); return res.json({success:true,data:payload}); } catch(e){return res.status(e.status||500).json({success:false,message:e.message});} });

router.patch('/:chatId/settings', async (req,res)=>{ try { const chat=await loadGroup(req.params.chatId); const actor=uid(req); await requireManager(chat,actor); const allowed=['allowMedia','allowCalls','allowReactions','allowReplies','allowEditing','allowDeleting','slowMode','requireAdminApproval']; const incoming=req.body?.settings||{}; const next={...(chat.settings||{})}; for(const key of allowed) if(Object.prototype.hasOwnProperty.call(incoming,key)) next[key]=incoming[key]; await chat.update({settings:next,updatedAt:new Date()}); const payload={groupId:chat.id,settings:next,updatedBy:actor,timestamp:new Date().toISOString()}; await emitGroup(req,'GROUP_SETTINGS_UPDATED',payload); await emitGroup(req,'group:settings:updated',payload); return res.json({success:true,data:{settings:next}}); } catch(e){return res.status(e.status||500).json({success:false,message:e.message}); } });

// Create/revoke/list shareable invite links. Tokens are random, opaque and
// stored in group metadata so they survive process restarts and deployments.
router.post('/:chatId/invites', async (req,res)=>{ try { const chat=await loadGroup(req.params.chatId); await requireManager(chat,uid(req)); const meta=metadata(chat); const invites=Array.isArray(meta.inviteLinks)?meta.inviteLinks.slice():[]; const token=crypto.randomBytes(24).toString('base64url'); const invite={token,createdBy:String(uid(req)),createdAt:new Date().toISOString(),uses:0,active:true}; invites.push(invite); meta.inviteLinks=invites.slice(-20); await saveMetadata(chat,meta); return res.status(201).json({success:true,data:invite}); }catch(e){return res.status(e.status||500).json({success:false,message:e.message});} });

router.get('/:chatId/invites', async(req,res)=>{try{const chat=await loadGroup(req.params.chatId);await requireManager(chat,uid(req));const meta=metadata(chat);return res.json({success:true,data:(meta.inviteLinks||[]).filter(x=>x.active!==false)});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

router.delete('/:chatId/invites/:token', async(req,res)=>{try{const chat=await loadGroup(req.params.chatId);await requireManager(chat,uid(req));const meta=metadata(chat);const invites=(meta.inviteLinks||[]).map(x=>x.token===req.params.token?{...x,active:false,revokedAt:new Date().toISOString()}:x);meta.inviteLinks=invites;await saveMetadata(chat,meta);return res.json({success:true});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

// Resolve an invite without revealing group membership. Authentication is
// still required by the application's global auth middleware.
router.get('/invite/:token', async(req,res)=>{try{const token=String(req.params.token||'');if(!token)return res.status(400).json({success:false,message:'Invite token is required'});const groups=await Chat.findAll({where:{type:'group',isActive:true}});const chat=groups.find(c=>(metadata(c).inviteLinks||[]).some(x=>x.token===token&&x.active!==false));if(!chat)return res.status(404).json({success:false,message:'Invite link is invalid or revoked'});return res.json({success:true,data:{chatId:chat.id,name:chat.name,description:chat.description,avatar:chat.avatar}});}catch(e){return res.status(500).json({success:false,message:'Unable to resolve invite'});}});

// Join by invite. If admin approval is enabled, create a durable pending
// request in metadata; otherwise add the authenticated user immediately.
router.post('/invite/:token/join', async(req,res)=>{try{const userId=uid(req);if(!userId)return res.status(401).json({success:false,message:'Authentication required'});const token=String(req.params.token||'');const groups=await Chat.findAll({where:{type:'group',isActive:true}});const chat=groups.find(c=>(metadata(c).inviteLinks||[]).some(x=>x.token===token&&x.active!==false));if(!chat)return res.status(404).json({success:false,message:'Invite link is invalid or revoked'});if(await membership(chat.id,userId))return res.json({success:true,data:{status:'already_member',chatId:chat.id}});const settings=chat.settings||{};const meta=metadata(chat);const requests=Array.isArray(meta.joinRequests)?meta.joinRequests.slice():[];const existing=requests.find(x=>String(x.userId)===String(userId)&&x.status==='pending');if(settings.requireAdminApproval){if(existing)return res.json({success:true,data:{status:'pending',requestId:existing.id}});const request={id:'jr_'+crypto.randomBytes(10).toString('hex'),userId:Number(userId),token,requestedAt:new Date().toISOString(),status:'pending'};requests.push(request);meta.joinRequests=requests.slice(-500);await saveMetadata(chat,meta);await emitGroup(req,'GROUP_JOIN_REQUEST', {groupId:chat.id,request,timestamp:new Date().toISOString()});return res.status(202).json({success:true,data:{status:'pending',requestId:request.id}});}await ChatParticipant.create({chatId:chat.id,userId:Number(userId),role:'member',joinedAt:new Date()});const invite=(meta.inviteLinks||[]).find(x=>x.token===token);if(invite){invite.uses=(invite.uses||0)+1;await saveMetadata(chat,meta);}await emitGroup(req,'GROUP_MEMBER_ADDED',{groupId:chat.id,member:{id:Number(userId),userId:Number(userId),role:'member'},addedBy:'invite',timestamp:new Date().toISOString()});return res.status(201).json({success:true,data:{status:'joined',chatId:chat.id}});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

router.get('/:chatId/join-requests', async(req,res)=>{try{const chat=await loadGroup(req.params.chatId);await requireManager(chat,uid(req));const meta=metadata(chat);const ids=(meta.joinRequests||[]).filter(x=>x.status==='pending').map(x=>x.userId);const users=ids.length?await User.findAll({where:{id:ids},attributes:['id','username','avatar','firstName','lastName']}):[];const byId=new Map(users.map(u=>[String(u.id),u]));return res.json({success:true,data:(meta.joinRequests||[]).filter(x=>x.status==='pending').map(x=>({...x,user:byId.get(String(x.userId))||null}))});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

router.patch('/:chatId/join-requests/:requestId', async(req,res)=>{try{const chat=await loadGroup(req.params.chatId);await requireManager(chat,uid(req));const action=req.body?.action==='approve'?'approve':'reject';const meta=metadata(chat);const requests=Array.isArray(meta.joinRequests)?meta.joinRequests.slice():[];const request=requests.find(x=>x.id===req.params.requestId&&x.status==='pending');if(!request)return res.status(404).json({success:false,message:'Join request not found'});if(action==='approve'){if(!(await membership(chat.id,request.userId)))await ChatParticipant.create({chatId:chat.id,userId:Number(request.userId),role:'member',joinedAt:new Date()});request.status='approved';request.resolvedBy=Number(uid(req));request.resolvedAt=new Date().toISOString();}else{request.status='rejected';request.resolvedBy=Number(uid(req));request.resolvedAt=new Date().toISOString();}meta.joinRequests=requests;await saveMetadata(chat,meta);await emitGroup(req,'GROUP_JOIN_REQUEST_RESOLVED',{groupId:chat.id,request,action,timestamp:new Date().toISOString()});return res.json({success:true,data:request});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

// Ownership transfer is intentionally owner-only and atomic at the logical
// application level: the new owner becomes owner through createdBy while the
// previous owner is retained as an administrator.
router.patch('/:chatId/ownership', async(req,res)=>{try{const chat=await loadGroup(req.params.chatId);const actor=uid(req);if(String(chat.createdBy)!==String(actor))return res.status(403).json({success:false,message:'Only the group owner can transfer ownership'});const targetId=Number(req.body?.userId);if(!Number.isInteger(targetId)||targetId<=0)return res.status(400).json({success:false,message:'Valid userId is required'});const target=await membership(chat.id,targetId);if(!target)return res.status(400).json({success:false,message:'New owner must already be a member'});chat.createdBy=targetId;await chat.save();const previous=await membership(chat.id,actor);if(previous){previous.role='admin';await previous.save();}target.role='admin';await target.save();const payload={groupId:chat.id,previousOwner:Number(actor),newOwner:targetId,timestamp:new Date().toISOString()};await emitGroup(req,'GROUP_OWNERSHIP_TRANSFERRED',payload);return res.json({success:true,data:payload});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

// A member can leave voluntarily. The owner must transfer ownership first;
// this prevents an ownerless group.
router.post('/:chatId/leave', async(req,res)=>{try{const chat=await loadGroup(req.params.chatId);const actor=uid(req);const p=await membership(chat.id,actor);if(!p)return res.status(404).json({success:false,message:'You are not a member of this group'});if(String(chat.createdBy)===String(actor))return res.status(409).json({success:false,message:'Transfer ownership before leaving the group'});await ChatParticipant.destroy({where:{chatId:chat.id,userId:actor}});await emitGroup(req,'GROUP_MEMBER_LEFT',{groupId:chat.id,userId:Number(actor),timestamp:new Date().toISOString()});return res.json({success:true});}catch(e){return res.status(e.status||500).json({success:false,message:e.message});}});

module.exports = router;
