'use strict';
const express=require('express'),router=express.Router(),db=require('../models');
const {authenticateToken}=require('../middleware/auth'),{apiRateLimiter}=require('../middleware/rateLimiter');
const delivery=require('../services/messageDeliveryService'),{broadcastNewMessage}=require('../services/messageBroadcast');
router.use(authenticateToken);router.use(apiRateLimiter);
const uid=req=>Number(req.user?.userId??req.user?.id??req.user?.sub),int=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null};
async function member(chatId,userId){const CP=db.ChatParticipant||db.models?.ChatParticipant;if(!CP)throw Object.assign(new Error('Chat membership service unavailable'),{status:503});const p=await CP.findOne({where:{chatId,userId}});if(!p)throw Object.assign(new Error('Not a participant of this chat'),{status:403});return p;}
try{router.use('/preview',require('./linkPreview'));}catch(e){console.warn('[messagingFeatures] preview:',e.message);}
router.get('/chats/pinned',async(req,res)=>{const CP=db.ChatParticipant||db.models?.ChatParticipant;const rows=await CP.findAll({where:{userId:uid(req),isPinned:true},attributes:['chatId','pinnedAt'],order:[['pinnedAt','DESC']]});res.json({success:true,data:rows.map(r=>String(r.chatId))});});
router.put('/chats/:chatId/pin',async(req,res)=>{const id=int(req.params.chatId);if(!id)return res.status(400).json({success:false,message:'Invalid chatId'});const p=await member(id,uid(req)),pinned=req.body?.pinned!==false;await p.update({isPinned:pinned,pinnedAt:pinned?new Date():null});res.json({success:true,data:{chatId:id,pinned}});});
router.get('/chats/:chatId/pinned',async(req,res)=>{const id=int(req.params.chatId);if(!id)return res.status(400).json({success:false,message:'Invalid chatId'});await member(id,uid(req));const Pin=db.models?.PinnedMessage||db.PinnedMessage,Message=db.Messages||db.Message;if(!Pin||!Message)return res.status(503).json({success:false,message:'Pin service unavailable'});const rows=await Pin.findAll({where:{chatId:id},order:[['pinnedAt','DESC']],limit:3});const pins=await Promise.all(rows.map(async p=>{const m=await Message.findByPk(p.messageId);return m?{...p.toJSON(),message:m.toJSON()}:null;}));res.json({success:true,data:{pinned:pins.filter(Boolean)}});});
router.post('/messages/:messageId/pin',async(req,res)=>{const mid=int(req.params.messageId),Message=db.Messages||db.Message,Pin=db.models?.PinnedMessage||db.PinnedMessage;if(!mid||!Message||!Pin)return res.status(400).json({success:false,message:'Invalid messageId'});const m=await Message.findByPk(mid);if(!m)return res.status(404).json({success:false,message:'Message not found'});await member(m.chatId,uid(req));const old=await Pin.findOne({where:{chatId:m.chatId,messageId:mid}});if(old)return res.json({success:true,data:old,alreadyPinned:true});if(await Pin.count({where:{chatId:m.chatId}})>=3)return res.status(409).json({success:false,message:'A chat can have at most 3 pinned messages'});const pin=await Pin.create({chatId:m.chatId,messageId:mid,pinnedBy:uid(req)});res.status(201).json({success:true,data:pin});});
router.delete('/messages/:messageId/pin',async(req,res)=>{const mid=int(req.params.messageId),Message=db.Messages||db.Message,Pin=db.models?.PinnedMessage||db.PinnedMessage;if(!mid||!Message||!Pin)return res.status(400).json({success:false,message:'Invalid messageId'});const m=await Message.findByPk(mid);if(!m)return res.status(404).json({success:false,message:'Message not found'});await member(m.chatId,uid(req));const removed=await Pin.destroy({where:{chatId:m.chatId,messageId:mid}});res.json({success:true,data:{removed:removed>0}});});
router.get('/chats/:chatId/search',async(req,res)=>{const id=int(req.params.chatId),q=String(req.query.q||'').trim().slice(0,200);if(!id||!q)return res.json({success:true,data:{results:[]}});await member(id,uid(req));const rows=await db.sequelize.query(`SELECT m.*,u.username AS "senderUsername",u.avatar AS "senderAvatar",u."firstName",u."lastName" FROM "Messages" m LEFT JOIN "Users" u ON u.id=m."senderId" WHERE m."chatId"=:id AND m."isDeleted"=false AND m.content ILIKE :q ORDER BY m."createdAt" DESC LIMIT 100`,{replacements:{id,q:`%${q}%`},type:db.sequelize.QueryTypes.SELECT});res.json({success:true,data:{results:rows}});});
router.get('/chats/:chatId/mentions',async(req,res)=>{const id=int(req.params.chatId);if(!id)return res.status(400).json({success:false,message:'Invalid chatId'});await member(id,uid(req));const q=String(req.query.q||'').trim().slice(0,80),rows=await db.sequelize.query(`SELECT u.id,u.username,u.avatar,u."firstName",u."lastName" FROM chat_participants cp JOIN "Users" u ON u.id=cp."userId" WHERE cp."chatId"=:id AND (:q='' OR u.username ILIKE :like OR u."firstName" ILIKE :like OR u."lastName" ILIKE :like) ORDER BY u.username LIMIT 20`,{replacements:{id,q,like:`%${q}%`},type:db.sequelize.QueryTypes.SELECT});res.json({success:true,data:{members:rows}});});
router.post('/messages/:messageId/report',async(req,res)=>{const mid=int(req.params.messageId),u=uid(req),reason=String(req.body?.reason||''),valid=['spam','harassment','hate_speech','violence','sexual_content','misinformation','other'];if(!mid||!valid.includes(reason))return res.status(400).json({success:false,message:'Invalid messageId or reason'});const [m]=await db.sequelize.query(`SELECT m.id,m."chatId",m."senderId" FROM "Messages" m JOIN chat_participants cp ON cp."chatId"=m."chatId" AND cp."userId"=:u WHERE m.id=:mid AND m."isDeleted"=false LIMIT 1`,{replacements:{u,mid},type:db.sequelize.QueryTypes.SELECT});if(!m)return res.status(404).json({success:false,message:'Message not found or access denied'});if(Number(m.senderId)===u)return res.status(400).json({success:false,message:'You cannot report your own message'});const Report=db.MessageReport||db.models?.MessageReport;if(!Report)return res.status(503).json({success:false,message:'Report service unavailable'});const [report]=await Report.findOrCreate({where:{reporterId:u,messageId:mid},defaults:{reporterId:u,messageId:mid,chatId:m.chatId,reason,details:String(req.body?.details||'').slice(0,500),status:'pending'}});res.json({success:true,data:{reportId:report.id}});});
router.post('/chats/:chatId/disappear',async(req,res)=>{const id=int(req.params.chatId),timer=Number(req.body?.timer||0),allowed=[0,86400,604800,2592000,7776000];if(!id||!allowed.includes(timer))return res.status(400).json({success:false,message:'Invalid disappearing timer'});await member(id,uid(req));const Chat=db.Chats||db.Chat,chat=await Chat.findByPk(id);if(!chat)return res.status(404).json({success:false,message:'Chat not found'});await chat.update({settings:{...(chat.settings||{}),disappearingTimer:timer||null}});res.json({success:true,data:{chatId:id,timer}});});
router.post('/scheduled',async(req,res)=>{const u=uid(req),id=int(req.body?.chatId),sendAt=new Date(req.body?.sendAt);if(!id||Number.isNaN(sendAt.getTime())||sendAt.getTime()<=Date.now())return res.status(400).json({success:false,message:'chatId and a future sendAt are required'});await member(id,u);const S=db.ScheduledMessage||db.models?.ScheduledMessage;if(!S)return res.status(503).json({success:false,message:'Scheduled message service unavailable'});const row=await S.create({userId:u,chatId:id,content:String(req.body?.content||'').slice(0,5000),type:String(req.body?.type||'text').slice(0,20),mediaUrl:req.body?.mediaUrl||null,metadata:req.body?.metadata&&typeof req.body.metadata==='object'?req.body.metadata:{},sendAt});res.status(201).json({success:true,data:{scheduled:row}});});
router.get('/scheduled',async(req,res)=>{const S=db.ScheduledMessage||db.models?.ScheduledMessage;if(!S)return res.status(503).json({success:false,message:'Scheduled message service unavailable'});const rows=await S.findAll({where:{userId:uid(req),status:'pending'},order:[['sendAt','ASC']],limit:100});res.json({success:true,data:{scheduled:rows}});});
router.delete('/scheduled/:id',async(req,res)=>{const id=int(req.params.id),S=db.ScheduledMessage||db.models?.ScheduledMessage;if(!id||!S)return res.status(400).json({success:false,message:'Invalid scheduled message'});const [count]=await S.update({status:'cancelled'},{where:{id,userId:uid(req),status:'pending'}});res.json({success:true,cancelled:count>0});});
router.post('/broadcast',async(req,res)=>{const senderId=uid(req),items=Array.isArray(req.body?.recipients)?req.body.recipients:[];if(!items.length||items.length>100)return res.status(400).json({success:false,message:'1-100 recipients required'});const batchId=String(req.body?.batchId||`b_${Date.now()}_${Math.random().toString(36).slice(2,10)}`),base=String(req.body?.content||''),type=String(req.body?.type||'text'),results=[];for(const item of items){const receiverId=int(item?.receiverId??item?.userId);if(!receiverId||receiverId===senderId)continue;const clientMessageId=String(item?.clientMessageId||`${batchId}_${receiverId}`).slice(0,64);try{const sent=await delivery.sendMessage({receiverId,senderId,content:item?.content??base,type,clientMessageId,metadata:{...(item?.metadata||{}),broadcastBatchId:batchId}});if(!sent.alreadyExisted)broadcastNewMessage(sent.message,senderId).catch(()=>{});results.push({receiverId,messageId:sent.message.id,alreadyExisted:!!sent.alreadyExisted,status:sent.message.status||'sent'});}catch(e){results.push({receiverId,failed:true,error:e.message,code:e.code||null});}}res.status(201).json({success:true,data:{batchId,results}});});
router.get('/broadcast/:batchId/status',async(req,res)=>{const u=uid(req),batchId=String(req.params.batchId||'').slice(0,100);const rows=await db.sequelize.query(`SELECT m.id AS "messageId",m."receiverId",m.status,m."sentAt",m."deliveredAt",rr."readAt",m."createdAt" FROM "Messages" m LEFT JOIN "ReadReceipts" rr ON rr."messageId"=m.id AND rr."userId"=m."receiverId" WHERE m."senderId"=:u AND m.metadata->>'broadcastBatchId'=:batchId ORDER BY m.id ASC`,{replacements:{u,batchId},type:db.sequelize.QueryTypes.SELECT});res.json({success:true,data:{batchId,results:rows}});});
module.exports=router;