'use strict';
const crypto=require('crypto');
const PIPELINE='KYN-GROUP-V2',ALGORITHM='SenderKey-AES256GCM-v2',MAX_HISTORY=100;
const now=()=>new Date().toISOString();
const fingerprint=m=>crypto.createHash('sha256').update(m.map(x=>Number(x.userId)).sort((a,b)=>a-b).join(',')).digest('hex');
function normalize(metadata){const r=metadata&&typeof metadata==='object'?metadata:{},g=r.groupMessaging&&typeof r.groupMessaging==='object'?r.groupMessaging:{};return{pipeline:PIPELINE,epoch:Math.max(0,Number(g.epoch)||0),fingerprint:g.fingerprint||null,algorithm:g.algorithm||ALGORITHM,pending:g.pending===true,reason:g.reason||null,pendingMemberIds:Array.isArray(g.pendingMemberIds)?g.pendingMemberIds.map(Number).filter(Number.isInteger):[],senderKeys:Array.isArray(g.senderKeys)?g.senderKeys:[],history:Array.isArray(g.history)?g.history:[],updatedAt:g.updatedAt||null}}
async function members(CP,g){const rows=await CP.findAll({where:{chatId:g},attributes:['userId','role']});return rows.map(r=>({userId:Number(r.userId),role:r.role}))}
async function loadGroup(db,g,u){const Chat=db.Chats||db.Chat,CP=db.ChatParticipant,chat=await Chat.findByPk(g);if(!chat||chat.type!=='group'||chat.isActive===false){const e=new Error('Group not found');e.status=404;throw e}if(!await CP.findOne({where:{chatId:g,userId:u}})){const e=new Error('You are not a member of this group');e.status=403;throw e}return{chat,ChatParticipant:CP}}
async function reconcile(chat,CP){const metadata={...(chat.metadata&&typeof chat.metadata==='object'?chat.metadata:{})},s=normalize(metadata),live=await members(CP,chat.id),fp=fingerprint(live);if(s.fingerprint&&s.fingerprint!==fp){if(s.epoch>0&&s.senderKeys.length)s.history=[...s.history,{epoch:s.epoch,senderKeys:s.senderKeys,algorithm:s.algorithm,timestamp:s.updatedAt||now()}].filter((x,i,a)=>a.findIndex(y=>Number(y.epoch)===Number(x.epoch))===i).slice(-MAX_HISTORY);s.epoch+=1;s.fingerprint=fp;s.pending=true;s.reason='membership_changed';s.senderKeys=[];s.updatedAt=now();metadata.groupMessaging=s;await chat.update({metadata,updatedAt:new Date()})}else if(!s.fingerprint){s.fingerprint=fp;s.pending=true;s.reason='initial_key';s.updatedAt=now();metadata.groupMessaging=s;await chat.update({metadata,updatedAt:new Date()})}return{state:s,members:live}}
function clean(d,o){const u=Number(d?.userId);if(!Number.isInteger(u)||u<1||typeof d?.ciphertext!=='string'||d.ciphertext.length>30000)return null;return{userId:u,deviceId:String(d.deviceId||'primary').slice(0,128),ciphertext:d.ciphertext,algorithm:String(d.algorithm||ALGORITHM).slice(0,80),ownerId:Number(o)}}
async function rotateSenderKey(chat,CP,actor,body){const {state,members:live}=await reconcile(chat,CP),epoch=Math.max(1,Number(state.epoch)||1);if(Number(body?.epoch)!==epoch){const e=new Error('Invalid group encryption epoch');e.status=409;e.currentEpoch=epoch;throw e}const allowed=new Set(live.map(x=>String(x.userId))),cleaned=(Array.isArray(body?.distributions)?body.distributions:[]).map(d=>clean(d,actor)).filter(Boolean);if(cleaned.some(d=>!allowed.has(String(d.userId)))){const e=new Error('Key distribution contains a non-member');e.status=403;throw e}const byUser=new Map(cleaned.map(d=>[String(d.userId),d])),missing=live.map(x=>x.userId).filter(id=>!byUser.has(String(id)));const metadata={...(chat.metadata&&typeof chat.metadata==='object'?chat.metadata:{})},fresh=normalize(metadata);fresh.pipeline=PIPELINE;fresh.epoch=epoch;fresh.fingerprint=fingerprint(live);fresh.algorithm=ALGORITHM;fresh.pending=missing.length>0;fresh.pendingMemberIds=missing;fresh.reason=missing.length?'delivery_pending':null;fresh.updatedAt=now();fresh.senderKeys=[...fresh.senderKeys.filter(x=>!(Number(x.ownerId)===Number(actor)&&Number(x.epoch)===epoch)),{ownerId:Number(actor),epoch,distributions:[...byUser.values()].map(d=>({...d,deliveryState:Number(d.userId)===Number(actor)?'installed':'pending',installedAt:Number(d.userId)===Number(actor)?fresh.updatedAt:null})),createdAt:fresh.updatedAt}];metadata.groupMessaging=fresh;await chat.update({metadata,updatedAt:new Date()});return{state:fresh,members:live}}
const currentKey=(s,o)=>s.senderKeys.find(x=>Number(x.ownerId)===Number(o)&&Number(x.epoch)===Number(s.epoch))||null;
const project=(keys,uid)=>keys.map(k=>({ownerId:Number(k.ownerId),epoch:Number(k.epoch),algorithm:k.algorithm||ALGORITHM,distribution:k.distributions?.find(d=>String(d.userId)===String(uid))||null})).filter(x=>x.distribution);
async function stateFor(chat,CP,uid){const {state,members:live}=await reconcile(chat,CP);return{pipeline:PIPELINE,groupId:chat.id,epoch:state.epoch,algorithm:state.algorithm,pending:state.pending,pendingMemberIds:state.pendingMemberIds,missingMemberIds:state.pendingMemberIds,reason:state.reason,memberCount:live.length,senderKeys:project(state.senderKeys,uid),history:state.history.map(h=>({epoch:Number(h.epoch),algorithm:h.algorithm||ALGORITHM,senderKeys:project(h.senderKeys||[],uid)})).filter(h=>h.senderKeys.length)}}
const envelope=c=>{try{const e=JSON.parse(c);return e&&e.v===2&&e.pipeline===PIPELINE&&Number.isInteger(Number(e.epoch))&&Number.isInteger(Number(e.owner))&&typeof e.iv==='string'&&typeof e.ct==='string'?e:null}catch(_){return null}};
async function insertMessage(db,g,sender,body){const e=envelope(body.content);if(!e){const x=new Error('Invalid group ciphertext envelope');x.status=400;throw x}const {chat,ChatParticipant:CP}=await loadGroup(db,g,sender),{state,members:live}=await reconcile(chat,CP);if(Number(e.epoch)!==Number(state.epoch)||Number(e.owner)!==Number(sender)){const x=new Error('Group sender key epoch is not active for this sender');x.status=409;x.code='GROUP_SENDER_KEY_NOT_ACTIVE';throw x}const k=currentKey(state,sender);if(!k||!k.distributions.some(d=>String(d.userId)===String(sender))){const x=new Error('Create your group sender key before sending');x.status=409;x.code='GROUP_SENDER_KEY_REQUIRED';throw x}const cid=String(body.clientMessageId||'').slice(0,64),q=db.sequelize;if(cid){const [old]=await q.query('SELECT * FROM "Messages" WHERE "chatId"=:g AND "senderId"=:s AND "clientMessageId"=:cid LIMIT 1',{replacements:{g,s:sender,cid},type:q.QueryTypes.SELECT});if(old)return{message:old,alreadyExisted:true}}const type=['text','image','video','audio','file','sticker','location','contact','system','poll','view_once'].includes(body.type)?body.type:'text',metadata={...(body.metadata&&typeof body.metadata==='object'?body.metadata:{}),groupId:Number(g),groupPipeline:PIPELINE,groupEpoch:Number(state.epoch),groupSender:Number(sender)};const [rows]=await q.query(`INSERT INTO "Messages" ("chatId","senderId","receiverId","content","type","clientMessageId","status","deliveryAttempts","reactions","metadata","sentAt","createdAt","updatedAt") VALUES (:g,:s,NULL,:content,:type,:cid,'sent',0,'{}'::jsonb,:metadata::jsonb,NOW(),NOW(),NOW()) RETURNING *`,{replacements:{g,s:sender,content:String(body.content),type,cid:cid||null,metadata:JSON.stringify(metadata)},type:q.QueryTypes.INSERT});const inserted=rows[0];
// Live group broadcasts must carry the same sender identity as history reloads.
// The INSERT ... RETURNING * only contains Message columns, so clients received
// senderId with no username/displayName/avatar and rendered the sender as "Member".
// Rehydrate the just-created row through the canonical Users join before emitting it.
const [message]=await q.query(`SELECT m.*,u.username AS "senderUsername",u.avatar AS "senderAvatar",u."firstName",u."lastName",u."displayName" AS "senderDisplayName" FROM "Messages" m LEFT JOIN "Users" u ON u.id=m."senderId" WHERE m.id=:id LIMIT 1`,{replacements:{id:inserted.id},type:q.QueryTypes.SELECT});
await chat.update({lastMessageId:message.id,lastMessageAt:message.createdAt,updatedAt:new Date()});return{message:message||inserted,alreadyExisted:false,members:live}}
async function emit(io,ids,event,payload){if(!io)return;for(const id of ids){try{io.to(`user:${id}`).emit(event,payload);io.to(`user_${id}`).emit(event,payload)}catch(_){}}}
async function invalidateMembership(chat,CP,reason='membership_changed',targetUserId=null){if(!chat||chat.type!=='group')return;const metadata={...(chat.metadata&&typeof chat.metadata==='object'?chat.metadata:{})},s=normalize(metadata),live=await members(CP,chat.id);if(s.epoch>0&&s.senderKeys.length)s.history=[...s.history,{epoch:s.epoch,senderKeys:s.senderKeys,algorithm:s.algorithm,timestamp:s.updatedAt||now()}].filter((x,i,a)=>a.findIndex(y=>Number(y.epoch)===Number(x.epoch))===i).slice(-MAX_HISTORY);s.epoch=Math.max(1,s.epoch+1);s.fingerprint=fingerprint(live);s.pending=true;s.reason=reason;s.senderKeys=[];s.updatedAt=now();metadata.groupMessaging=s;await chat.update({metadata,updatedAt:new Date()});await emit(global.__socketIO,live.map(x=>x.userId),'group:security:epoch',{groupId:chat.id,epoch:s.epoch,pipeline:PIPELINE,reason,targetUserId})}
async function acknowledgeSenderKey(db,g,uid,owner,epoch){const {chat,ChatParticipant:CP}=await loadGroup(db,g,uid),{state,members:live}=await reconcile(chat,CP),ownerId=Number(owner),ep=Number(epoch),entry=state.senderKeys.find(x=>Number(x.ownerId)===ownerId&&Number(x.epoch)===ep);if(!entry){const e=new Error('Sender key distribution not found');e.status=404;throw e}const d=entry.distributions?.find(x=>String(x.userId)===String(uid));if(!d){const e=new Error('Sender key is not assigned to this member');e.status=403;throw e}d.deliveryState='installed';d.installedAt=now();// Recompute delivery state across every active sender key in the current epoch.
  // Looking only at the key that happened to be acknowledged could incorrectly
  // clear the group's pending state while another member's sender key still had
  // undelivered recipients.
  const activeKeys=state.senderKeys.filter(x=>Number(x.epoch)===ep);
  const pendingSet=new Set();
  for(const k of activeKeys){
    for(const member of live){
      const d=k.distributions?.find(x=>Number(x.userId)===Number(member.userId));
      if(!d||d.deliveryState!=='installed')pendingSet.add(Number(member.userId));
    }
  }
  state.pendingMemberIds=[...pendingSet];
  state.pending=state.pendingMemberIds.length>0;
  state.reason=state.pending?'delivery_pending':null;state.updatedAt=now();const metadata={...(chat.metadata&&typeof chat.metadata==='object'?chat.metadata:{})};metadata.groupMessaging=state;await chat.update({metadata,updatedAt:new Date()});return{groupId:Number(g),ownerId,epoch:ep,installedBy:Number(uid),pendingMemberIds:state.pendingMemberIds,pending:state.pending}}
async function updateMessage(db,id,userId,content){const q=db.sequelize,[m]=await q.query(`SELECT * FROM "Messages" WHERE id=:id AND "senderId"=:u AND "isDeleted"=false AND (metadata->>'groupPipeline')=:p LIMIT 1`,{replacements:{id,u:userId,p:PIPELINE},type:q.QueryTypes.SELECT});if(!m){const e=new Error('Group message not found or not owned by you');e.status=404;throw e}const e=envelope(content);if(!e||Number(e.owner)!==Number(userId)){const x=new Error('Invalid group edit envelope');x.status=400;throw x}await q.query('UPDATE "Messages" SET content=:content,"isEdited"=true,"editedAt"=NOW(),"updatedAt"=NOW() WHERE id=:id',{replacements:{id,content}});return{...m,content,isEdited:true}}
async function deleteMessage(db,id,userId,forEveryone){const q=db.sequelize,[m]=await q.query(`SELECT id,"chatId","senderId",metadata,"createdAt" FROM "Messages" WHERE id=:id AND "isDeleted"=false AND (metadata->>'groupPipeline')=:p LIMIT 1`,{replacements:{id,p:PIPELINE},type:q.QueryTypes.SELECT});if(!m){const e=new Error('Group message not found');e.status=404;throw e}const [member]=await q.query('SELECT 1 FROM chat_participants WHERE "chatId"=:g AND "userId"=:u LIMIT 1',{replacements:{g:m.chatId,u:userId},type:q.QueryTypes.SELECT});if(!member){const e=new Error('Not a member of this group');e.status=403;throw e}if(forEveryone){if(Number(m.senderId)!==Number(userId)){const e=new Error('Only the sender can delete for everyone');e.status=403;throw e}await q.query('UPDATE "Messages" SET "isDeleted"=true,"deletedAt"=NOW(),"deletedBy"=:u,"updatedAt"=NOW() WHERE id=:id',{replacements:{id,u:userId}})}else{let md={};try{md=typeof m.metadata==='string'?JSON.parse(m.metadata):m.metadata||{}}catch(_){}const a=Array.isArray(md.deletedFor)?md.deletedFor:[];if(!a.includes(userId))a.push(userId);md.deletedFor=a;await q.query('UPDATE "Messages" SET metadata=:metadata::jsonb,"updatedAt"=NOW() WHERE id=:id',{replacements:{id,metadata:JSON.stringify(md)}})}return m}
module.exports={PIPELINE,ALGORITHM,normalize,members,loadGroup,reconcile,rotateSenderKey,stateFor,insertMessage,parseEnvelope:envelope,emit,invalidateMembership,acknowledgeSenderKey,updateMessage,deleteMessage};