'use strict';
let _admin=null,_app=null,_ready=false,_initErr=null;
function _initFirebase(){if(_ready||_initErr)return;try{_admin=require('firebase-admin');let credential;if(process.env.FIREBASE_SERVICE_ACCOUNT){credential=_admin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT));}else if(process.env.FIREBASE_PROJECT_ID&&process.env.FIREBASE_CLIENT_EMAIL&&process.env.FIREBASE_PRIVATE_KEY){credential=_admin.credential.cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:String(process.env.FIREBASE_PRIVATE_KEY).replace(/\\n/g,'\n')});}else{_initErr='Firebase not configured';return;} _app=_admin.apps.length?_admin.apps[0]:_admin.initializeApp({credential});_ready=true;console.log('[PushService] Firebase Admin initialized');}catch(e){_initErr=e.message;console.warn('[PushService] Firebase init unavailable:',e.message);}}
_initFirebase();
function isConfigured(){return _ready;} function _db(){return require('../models');}
function _invalidError(code){return code==='messaging/registration-token-not-registered'||code==='messaging/invalid-registration-token'||code==='registration-token-not-registered'||code==='invalid-registration-token';}
function _stringData(data={}){return Object.fromEntries(Object.entries(data).map(([k,v])=>[String(k),String(v??'')]));}
async function _ensureTable(){const db=_db();await db.sequelize.query('CREATE TABLE IF NOT EXISTS device_push_tokens (id BIGSERIAL PRIMARY KEY,"userId" INTEGER NOT NULL,token TEXT NOT NULL UNIQUE,platform VARCHAR(30) NOT NULL DEFAULT \'android\',"userAgent" TEXT,"lastSeenAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())').catch(()=>{});}
async function _deleteTokens(tokens){if(!tokens?.length)return;try{const db=_db();await db.sequelize.query('DELETE FROM device_push_tokens WHERE token = ANY(:tokens)',{replacements:{tokens},type:db.sequelize.QueryTypes.DELETE});}catch(e){console.warn('[PushService] token cleanup failed:',e.message);}}
async function sendToMultipleTokens(tokens,notification,data={}){if(!_ready||!_app||!Array.isArray(tokens)||!tokens.length)return{successCount:0,failureCount:0,invalidTokens:[]};const invalidTokens=[];let successCount=0,failureCount=0;for(let i=0;i<tokens.length;i+=500){const batch=tokens.slice(i,i+500);try{const msg={notification:{title:String(notification.title||'Necpra').slice(0,80),body:String(notification.body||'').slice(0,300),...(/^https:\/\/[^\s]+$/i.test(String(notification.imageUrl||''))?{imageUrl:String(notification.imageUrl)}:{})},data:_stringData(data),android:{priority:'high',ttl:86400000,notification:{channelId:data.channelId||'messages',sound:'default'}},apns:{payload:{aps:{sound:'default',badge:1}}},tokens:batch};const response=await _admin.messaging().sendEachForMulticast(msg);successCount+=response.successCount;failureCount+=response.failureCount;response.responses.forEach((item,index)=>{if(item.success)return;if(_invalidError(item.error?.code))invalidTokens.push(batch[index]);else console.warn('[PushService] FCM send failed:',item.error?.code,item.error?.message);});}catch(e){console.error('[PushService] multicast failed:',e.message);failureCount+=batch.length;}}if(invalidTokens.length)await _deleteTokens([...new Set(invalidTokens)]);return{successCount,failureCount,invalidTokens};}
async function sendToToken(token,notification,data={}){const r=await sendToMultipleTokens([token],notification,data);return r.successCount?'sent':(r.invalidTokens.length?'INVALID_TOKEN':null);}
function _prefs(settings){const n=settings?.notifications||{};return{enabled:n.enableNotifications!==false&&n.pushNotifications!==false,messages:n.messageNotifications!==false&&n.messages!==false,groups:n.groupNotifications!==false&&n.groups!==false,status:n.statusNotifications!==false&&n.status!==false};}
async function _tokensForUsers(userIds,category){await _ensureTable();const db=_db(),ids=[...new Set((userIds||[]).map(Number).filter(Number.isInteger))];if(!ids.length)return[];const rows=await db.sequelize.query('SELECT d."userId",d.token,u.settings FROM device_push_tokens d JOIN "Users" u ON u.id=d."userId" WHERE d."userId"=ANY(:ids) AND d."lastSeenAt">NOW()-INTERVAL \'90 days\' AND d.token IS NOT NULL AND d.token<>\'\'',{replacements:{ids},type:db.sequelize.QueryTypes.SELECT});return rows.filter(r=>{const p=_prefs(r.settings);return p.enabled&&p[category]!==false;});}
let _warnedNoFirebase=false;
async function sendToUsers(userIds,notification,data={},options={}){if(!_ready){if(!_warnedNoFirebase){_warnedNoFirebase=true;console.warn('[PushService] Push is DISABLED - Firebase Admin not initialised:',_initErr||'unknown reason','(set FIREBASE_SERVICE_ACCOUNT on Render)');}return{successCount:0,failureCount:0,invalidTokens:[],configured:false};}const category=options.category||'messages';const rows=await _tokensForUsers(userIds,category);const channel=data.channelId||(category==='groups'?'group_messages':category==='status'?'status_updates':category==='other'?'general':'messages');return{...(await sendToMultipleTokens(rows.map(r=>r.token),notification,{...data,channelId:channel})),configured:true};}
async function registerToken(userId,token,meta={}){await _ensureTable();const uid=Number(userId),fcmToken=String(token||'').trim();if(!uid||!fcmToken)throw new Error('userId and token are required');const db=_db();await db.sequelize.query('INSERT INTO device_push_tokens ("userId",token,platform,"userAgent","lastSeenAt","createdAt","updatedAt") VALUES (:userId,:token,:platform,:userAgent,NOW(),NOW(),NOW()) ON CONFLICT (token) DO UPDATE SET "userId"=EXCLUDED."userId",platform=EXCLUDED.platform,"userAgent"=EXCLUDED."userAgent","lastSeenAt"=NOW(),"updatedAt"=NOW()',{replacements:{userId:uid,token:fcmToken,platform:String(meta.platform||'android').slice(0,30),userAgent:meta.userAgent?String(meta.userAgent).slice(0,1000):null},type:db.sequelize.QueryTypes.INSERT});return true;}
async function unregisterToken(userId,token=null){await _ensureTable();const uid=Number(userId);if(!uid)return false;const db=_db();await db.sequelize.query(token?'DELETE FROM device_push_tokens WHERE "userId"=:userId AND token=:token':'DELETE FROM device_push_tokens WHERE "userId"=:userId',{replacements:token?{userId:uid,token:String(token)}:{userId:uid},type:db.sequelize.QueryTypes.DELETE});return true;}
async function getStatus(userId){await _ensureTable();const db=_db(),uid=Number(userId);const rows=uid?await db.sequelize.query('SELECT COUNT(*)::int AS count FROM device_push_tokens WHERE "userId"=:userId',{replacements:{userId:uid},type:db.sequelize.QueryTypes.SELECT}):[];return{configured:_ready,error:_initErr,deviceCount:rows[0]?.count||0};}
async function pushGroupMessage(groupId,message,groupName='Group'){const db=_db(),GM=db.models?.GroupMembers||db.GroupMembers;if(!GM)return;const {Op}=require('sequelize');const members=await GM.findAll({where:{groupId,leftAt:null,isBanned:false,userId:{[Op.ne]:Number(message.senderId)},[Op.or]:[{mutedUntil:null},{mutedUntil:{[Op.lt]:new Date()}}]},attributes:['userId']});const ids=members.map(m=>Number(m.userId)).filter(Boolean);if(!ids.length)return;await sendToUsers(ids,{title:String(message.senderName||'Someone')+' in '+groupName,body:String(message.content||'New message').slice(0,120)},{type:'group_message',groupId:String(groupId),messageId:String(message.id||''),senderId:String(message.senderId||''),url:'/chat.html?groupId='+groupId},{category:'groups'});}

function _looksEncrypted(raw){return /^\s*\{\s*"(v|kid|ct|iv|eph|sid|n|pipeline|epoch|owner)"\s*:/.test(String(raw||''));}
function safePreview(message){const type=String(message?.type||'text').toLowerCase(),raw=String(message?.content||'');const labels={image:'a photo',video:'a video',audio:'a voice message',file:'a file',sticker:'a sticker',location:'a location',contact:'a contact',poll:'a poll'};if(type==='text')return(!raw||_looksEncrypted(raw))?'New message':raw.slice(0,100);return 'Sent '+(labels[type]||'a message');}
async function describeGroupMessage(groupId,message){let groupName='Group';try{const db=_db();const [c]=await db.sequelize.query('SELECT name FROM chats WHERE id=:id LIMIT 1',{replacements:{id:Number(groupId)},type:db.sequelize.QueryTypes.SELECT});if(c&&c.name)groupName=String(c.name);}catch(_){}const full=[message?.firstName,message?.lastName].filter(Boolean).join(' ').trim();const sender=message?.senderDisplayName||full||message?.senderUsername||'Someone';return{title:groupName,body:sender+': '+safePreview(message),imageUrl:message?.senderAvatar||null};}
// Generic bridge: every in-app Notification row (friend request, status like/comment, group invite, ...) also becomes an OS push.
function _channelForType(t){t=String(t||'');if(t.startsWith('status'))return'status_updates';if(t.startsWith('group'))return'group_messages';return'general';}
async function pushForNotification(userId,n){if(!n||!userId)return;const d=(n.data&&typeof n.data==='object')?n.data:{};const out={type:String(n.type||'notification'),notificationId:String(n.id||''),channelId:_channelForType(n.type),url:String(n.actionUrl||'')};['chatId','groupId','statusId','messageId','requesterId','userId'].forEach(k=>{if(d[k]!=null)out[k]=String(d[k]);});const category=String(n.type||'').startsWith('status')?'status':String(n.type||'').startsWith('group')?'groups':'other';await sendToUsers([Number(userId)],{title:String(n.title||'Necpra'),body:String(n.body||'You have a new notification'),imageUrl:d.senderAvatar||d.requesterAvatar||d.avatar||null},out,{category});}
module.exports={safePreview,describeGroupMessage,pushForNotification,sendToToken,sendToMultipleTokens,sendToUsers,pushGroupMessage,registerToken,unregisterToken,getStatus,isConfigured};