'use strict';
async function ensureStatusSchema(db){
 const qi=db.sequelize.getQueryInterface(), S=db.sequelize.Sequelize||require('sequelize');
 const exists=async n=>(await qi.showAllTables()).some(t=>String(t).toLowerCase()===n.toLowerCase());
 const add=async(c,d)=>{const x=await qi.describeTable('Status');if(!x[c])await qi.addColumn('Status',c,d);};
 if(!(await exists('Status')))await qi.createTable('Status',{id:{type:S.INTEGER,primaryKey:true,autoIncrement:true},userId:{type:S.INTEGER,allowNull:false},content:{type:S.TEXT},type:{type:S.STRING(24),allowNull:false,defaultValue:'text'},createdAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW},updatedAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW}});
 const c={mediaUrl:{type:S.TEXT},mediaPublicId:{type:S.STRING(500)},mediaMime:{type:S.STRING(120)},thumbnailUrl:{type:S.TEXT},caption:{type:S.TEXT},background:{type:S.STRING(120)},font:{type:S.STRING(80)},musicUrl:{type:S.TEXT},linkUrl:{type:S.TEXT},mentions:{type:S.JSONB,allowNull:false,defaultValue:[]},stickers:{type:S.JSONB,allowNull:false,defaultValue:[]},topics:{type:S.JSONB,allowNull:false,defaultValue:[]},moodType:{type:S.STRING(60)},category:{type:S.STRING(60)},intent:{type:S.STRING(60)},privacy:{type:S.STRING(40),allowNull:false,defaultValue:'all_contacts'},privacyList:{type:S.JSONB,allowNull:false,defaultValue:[]},durationSeconds:{type:S.INTEGER,allowNull:false,defaultValue:7},allowReplies:{type:S.BOOLEAN,allowNull:false,defaultValue:true},allowReactions:{type:S.BOOLEAN,allowNull:false,defaultValue:true},allowSharing:{type:S.BOOLEAN,allowNull:false,defaultValue:true},isPublic:{type:S.BOOLEAN,allowNull:false,defaultValue:false},isActive:{type:S.BOOLEAN,allowNull:false,defaultValue:true},expiresAt:{type:S.DATE,allowNull:false,defaultValue:S.literal("CURRENT_TIMESTAMP + INTERVAL '24 hours'")},viewCount:{type:S.INTEGER,allowNull:false,defaultValue:0},reactionCount:{type:S.INTEGER,allowNull:false,defaultValue:0},replyCount:{type:S.INTEGER,allowNull:false,defaultValue:0},shareCount:{type:S.INTEGER,allowNull:false,defaultValue:0},highlight:{type:S.BOOLEAN,allowNull:false,defaultValue:false},pollOptions:{type:S.JSONB,allowNull:false,defaultValue:[]}};
 for(const[k,v]of Object.entries(c))await add(k,v);
 const t=[
 ['StatusViews',{id:{type:S.INTEGER,primaryKey:true,autoIncrement:true},statusId:{type:S.INTEGER,allowNull:false},viewerId:{type:S.INTEGER,allowNull:false},viewedAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW},createdAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW},updatedAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW}}],
 ['StatusReactions',{id:{type:S.INTEGER,primaryKey:true,autoIncrement:true},statusId:{type:S.INTEGER,allowNull:false},userId:{type:S.INTEGER,allowNull:false},emoji:{type:S.STRING(16),allowNull:false,defaultValue:'❤️'},createdAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW},updatedAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW}}],
 ['StatusReplies',{id:{type:S.INTEGER,primaryKey:true,autoIncrement:true},statusId:{type:S.INTEGER,allowNull:false},userId:{type:S.INTEGER,allowNull:false},text:{type:S.TEXT,allowNull:false},createdAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW},updatedAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW}}],
 ['StatusReports',{id:{type:S.INTEGER,primaryKey:true,autoIncrement:true},statusId:{type:S.INTEGER,allowNull:false},reporterId:{type:S.INTEGER,allowNull:false},reason:{type:S.STRING(80),allowNull:false},details:{type:S.TEXT},createdAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW},updatedAt:{type:S.DATE,allowNull:false,defaultValue:S.NOW}}]];
 for(const[n,cols]of t)if(!(await exists(n)))await qi.createTable(n,cols);
}
module.exports={ensureStatusSchema};