const config = require('./index');

// FIXED: Validate environment variables — hard-fail only on secret, use defaults for optional fields
if (!config.jwt || !config.jwt.secret) {
  throw new Error('JWT_SECRET is not configured in environment variables');
}

// Use defaults for optional issuer/audience — don't crash if missing
if (!config.jwt.issuer) {
  config.jwt.issuer = process.env.JWT_ISSUER || 'moodchat-api';
}

if (!config.jwt.audience) {
  config.jwt.audience = process.env.JWT_AUDIENCE || 'moodchat-client';
}

// Validate expiration times
if (!config.jwt.accessExpiration) {
  // PHASE15 FIX: Default was 15m which conflicts with tokenService.js default of 24h.
  // Both must agree or tokens generated by one service fail verification elsewhere.
  // 24h matches tokenService.js and the frontend session/storage TTL expectations.
  console.warn('JWT_ACCESS_EXPIRATION not set, using default: 24h');
  config.jwt.accessExpiration = '24h';
}

if (!config.jwt.refreshExpiration) {
  console.warn('JWT_REFRESH_EXPIRATION not set, using default: 7d');
  config.jwt.refreshExpiration = '7d';
}

// Validate algorithms
if (!config.jwt.accessToken || !config.jwt.accessToken.algorithm) {
  config.jwt.accessToken = config.jwt.accessToken || {};
  config.jwt.accessToken.algorithm = 'HS256';
}

if (!config.jwt.refreshToken || !config.jwt.refreshToken.algorithm) {
  config.jwt.refreshToken = config.jwt.refreshToken || {};
  config.jwt.refreshToken.algorithm = 'HS256';
}

module.exports = {
  secret: config.jwt.secret,
  audience: config.jwt.audience,
  issuer: config.jwt.issuer,

  accessToken: {
    expiresIn: config.jwt.accessExpiration,
    algorithm: config.jwt.accessToken.algorithm,
  },

  refreshToken: {
    expiresIn: config.jwt.refreshExpiration,
    algorithm: config.jwt.refreshToken.algorithm,
  },

  verificationToken: {
    expiresIn: '24h',
  },

  passwordResetToken: {
    expiresIn: '1h',
  },
  
  // Add tokenService configuration
  tokenService: {
    accessSecret: process.env.JWT_ACCESS_SECRET || process.env.JWT_SECRET,
    refreshSecret: process.env.JWT_REFRESH_SECRET || process.env.JWT_SECRET,
    accessExpiresIn: process.env.JWT_ACCESS_EXPIRES_IN || '24h',
    refreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '7d'
  },

  // ── CANONICAL SECRET RESOLUTION (FIX: Forensic Audit P0) ──────────────────
  // All modules MUST use these instead of reading process.env directly.
  // Priority matches tokenService.js: JWT_ACCESS_SECRET first, JWT_SECRET fallback.
  // Inconsistent priority in authController and authService caused token verify
  // failures when JWT_SECRET !== JWT_ACCESS_SECRET in production environments.
  canonicalAccessSecret:  process.env.JWT_ACCESS_SECRET  || process.env.JWT_SECRET,
  canonicalRefreshSecret: process.env.JWT_REFRESH_SECRET || process.env.JWT_SECRET,
};